server:
  port: 9030

spring:
  application:
    name: machine-search
  data:
    elasticsearch:
      cluster-name: rainbow
      cluster-nodes: 172.16.74.241:9300,172.16.74.242:9300,172.16.74.243:9300
