server:
  port: 9011

spring:
  application:
    name: talk-greeting
  zipkin:
    base-url: http://localhost:9200
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    sampler:
      percentage: 1

eureka:
  instance:
    hostname: localhost
    appname: talk-greeting
    # 启用ip配置 这样在注册中心列表中看见的是以ip+端口呈现的
    prefer-ip-address: true
    # 实例名称  最后呈现地址：ip:9020
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      cluster: talk-greeting
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 9000
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/

#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true

#跟踪调用链需要
logging:
  level:
    org.springframework.cloud: debug