server:
  port: 9030

spring:
  application:
    name: machine-search
  data:
    elasticsearch:
      cluster-name: rainbow
      cluster-nodes: 172.16.74.241:9200,172.16.74.242:9200,172.16.74.243:9200

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: debug